### ISSUE TITLE
smartpool deliverables

### ISSUE THREAD

**Issue by housemobile** [SmartPool/SmartPool.github.io#12]
Targeted Deliverables:

> Depending on how much we get, our promised deliverables vary as follows.
Less than 5,000 ETH: Implement SmartPool for Ethereum and release all software as open source (i.e. under MIT license).

> 5,000 to 10,000 ETH: In addition to what we have promised, we will launch a decentralized pool for Ethereum and maintain it until Ethereum moves to proof of stake.

With the 4x increase in ETH since donation period, is it possible SmartPool will be able to meet the 2nd targeted deliverable stage with current donations?

**Comment by loiluu** [comment]
Hi @housemobile,

Thanks for reaching out.
We will address your concern it in our next blog post (with a testnet release) in a couple of days. Please stay tuned.
